### ISSUE TITLE
printing add Tensor throwing NPE

### ISSUE THREAD

**Issue by chandu0101** [eaplatanios/tensorflow_scala#11]
```scala
 val node1 = tf.placeholder(tf.FLOAT64)
  val node2 = tf.placeholder(tf.FLOAT64)
  val adder = tf.add(node1, node2)
  println(s"Adder : ${adder}")
```

***StackTrace***

```scala
[error] (run-main-d) java.lang.NullPointerException
java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofLong$.length$extension(ArrayOps.scala:257)
        at scala.collection.mutable.ArrayOps$ofLong.length(ArrayOps.scala:257)
        at scala.collection.SeqLike.size(SeqLike.scala:105)
        at scala.collection.SeqLike.size$(SeqLike.scala:105)
        at scala.collection.mutable.ArrayOps$ofLong.size(ArrayOps.scala:251)
        at scala.collection.IndexedSeqLike.sizeHintIfCheap(IndexedSeqLike.scala:96)
        at scala.collection.IndexedSeqLike.sizeHintIfCheap$(IndexedSeqLike.scala:96)
        at scala.collection.mutable.ArrayOps$ofLong.sizeHintIfCheap(ArrayOps.scala:251)
        at scala.collection.mutable.Builder.sizeHint(Builder.scala:77)
        at scala.collection.mutable.Builder.sizeHint$(Builder.scala:76)
        at scala.collection.mutable.Builder$$anon$1.sizeHint(Builder.scala:132)
        at scala.collection.TraversableLike.builder$1(TraversableLike.scala:230)
        at scala.collection.TraversableLike.map(TraversableLike.scala:233)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.mutable.ArrayOps$ofLong.map(ArrayOps.scala:251)
        at org.platanios.tensorflow.api.ops.Output.$anonfun$shape$1(Output.scala:165)
        at org.platanios.tensorflow.api.package$.using(package.scala:58)
        at org.platanios.tensorflow.api.ops.Output.shape(Output.scala:164)
        at org.platanios.tensorflow.api.ops.Output.toString(Output.scala:264)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at scala.StringContext.standardInterpolator(StringContext.scala:125)
        at scala.StringContext.s(StringContext.scala:95)
        at example.Hello$.delayedEndpoint$example$Hello$1(Hello.scala:10)
        at example.Hello$delayedInit$body.apply(Hello.scala:6)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at example.Hello$.main(Hello.scala:6)
        at example.Hello.main(Hello.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```
 not a blocker , just reporting as i found it ...

**Comment by eaplatanios** [comment]
Fixed. Thanks for reporting this! :)
