### ISSUE TITLE
compile failed on win10_x64

### ISSUE THREAD

**Issue by ztaoo** [eaplatanios/tensorflow_scala#15]
when i run: sbt
i got:
```
D:\workstation\github\tensorflow_scala>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=400m; support was removed in 8.0
[info] Loading global plugins from C:\Users\Tao\.sbt\0.13\plugins
[info] Loading project definition from D:\workstation\github\tensorflow_scala\project
[error] Error trying to determine platform.
[warn] Cannot determine platform! It will be set to 'unknown'.
[info] Set current project to all (in build file:/D:/workstation/github/tensorflow_scala/)
>
```

then i run `compile`,
error got:
```
> compile
[info] Building library with native build tool CMake
Exception in thread "Thread-3" java.io.IOException: Cannot run program "cmake" (in directory "D:\workstation\github\tensorflow_scala\tensorflow\target\native\unknown-unk
nown\build"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.SequentialProcess.runAndExitValue(ProcessImpl.scala:240)
        at sbt.CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:201)
        at sbt.Spawn$$anon$3.run(ProcessImpl.scala:17)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Exception in thread "Thread-1" java.lang.RuntimeException: No exit code: process destroyed.
        at scala.sys.package$.error(package.scala:27)
        at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
        at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.CompoundProcess.exitValue(ProcessImpl.scala:193)
        at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply$mcI$sp(ProcessImpl.scala:241)
        at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply(ProcessImpl.scala:241)
        at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply(ProcessImpl.scala:241)
        at sbt.CompoundProcess.runInterruptible(ProcessImpl.scala:214)
        at sbt.SequentialProcess.runAndExitValue(ProcessImpl.scala:241)
        at sbt.CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:201)
        at sbt.Spawn$$anon$3.run(ProcessImpl.scala:17)
[info] Compiling 1 protobuf files to D:\workstation\github\tensorflow_scala\tensorflow\src\main\generated\java
[info] Compiling schema D:\workstation\github\tensorflow_scala\tensorflow\src\main\proto\CheckpointState.proto
[trace] Stack trace suppressed: run last tensorflow/*:nativeCompile for the full output.
[trace] Stack trace suppressed: run last tensorflow/protobuf:protobufGenerate for the full output.
[error] (tensorflow/*:nativeCompile) No exit code: process destroyed.
[error] (tensorflow/protobuf:protobufGenerate) error occurred while compiling protobuf files: Cannot run program "protoc": CreateProcess error=2, The system cannot find
the file specified
[error] Total time: 1 s, completed Jul 18, 2017 9:10:58 AM

```

what is  `[error] Error trying to determine platform.` about?

**Comment by eaplatanios** [comment]
This is because the `sbt-jni` plugin does not currently support Windows. It shouldn't be too hard to add support for Windows (the related issue is [here](https://github.com/jodersky/sbt-jni/issues/20)). If nothing happens for some time, I might tackle it, but I want to prioritize some features first.

**Comment by eaplatanios** [comment]
@ztaoo Could you please check if you can compile the library now, after my last commit?

**Comment by eaplatanios** [comment]
Closing due to inactivity.
