### ISSUE TITLE
org.platanios.tensorflow.jni.FailedPreconditionException: Input 1 ('Constant') for 'Conv2D' was not previously added to ShapeRefiner.

### ISSUE THREAD

**Issue by evan-wehi** [eaplatanios/tensorflow_scala#157]
I'm updating my code from 0.2 to 0.4 and I'm now getting this exception:
```
2019-03-11 11:14:02.085766: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Exception in thread "main" org.platanios.tensorflow.jni.FailedPreconditionException: Input 1 ('Constant') for 'Conv2D' was not previously added to ShapeRefiner.
	at org.platanios.tensorflow.jni.Op$.finish(Native Method)
	at org.platanios.tensorflow.api.ops.Op$Builder.$anonfun$build$1(Op.scala:2646)
	at org.platanios.tensorflow.api.utilities.package$.using(package.scala:31)
	at org.platanios.tensorflow.api.ops.Op$Builder.build(Op.scala:2589)
	at org.platanios.tensorflow.api.ops.NN.conv2D(NN.scala:1240)
	at org.platanios.tensorflow.api.ops.NN.conv2D$(NN.scala:1219)
	at org.platanios.tensorflow.api.package$tf$.conv2D(package.scala:294)
	at Conv2DFail$.$anonfun$main$1(Conv2DFail.scala:11)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.platanios.tensorflow.api.ops.Op$.createWith(Op.scala:2043)
	at org.platanios.tensorflow.api.ops.package$API.createWith(package.scala:120)
	at org.platanios.tensorflow.api.ops.package$API.createWith$(package.scala:114)
	at org.platanios.tensorflow.api.package$tf$.createWith(package.scala:294)
	at Conv2DFail$.main(Conv2DFail.scala:9)
	at Conv2DFail.main(Conv2DFail.scala)
```

The following recreates the problem:
```
import org.platanios.tensorflow.api.core.Shape
import org.platanios.tensorflow.api.ops.NN.SameConvPadding
import org.platanios.tensorflow.api.{Graph, Output, Tensor, tf}

object Conv2DFail {

  def main(args: Array[String]): Unit = {
    val kernels: Output[Float] = Tensor.randn(Float, Shape(3, 3, 3, 64))
    tf.createWith(graph = Graph(), device = "/CPU:0") {
      val inp: Output[Float] = Tensor.randn(Float, Shape(1, 45, 60, 3))
      tf.conv2D(inp, kernels, 1L, 1L, SameConvPadding)
    }
  }

}
```

If the `kernels` are created inside the `createWith` it works. 

Perhaps I'm using the API incorrectly, but I need to use the kernels in multiple graphs to manage GPU memory.

**Comment by eaplatanios** [comment]
This happens because `kernels` is placed on a different graph than `inp`. I'm not sure why this was working for you before, but it shouldn't have been. If you move the `kernels` declaration inside your `tf.createWith` block, it should work fine.

**Comment by evan-wehi** [comment]
It's a port of a python code that did the same thing, although in that case the I think the kernels were in numpy arrays. I don't know if that makes a difference.

I have problems with GPU memory so I create a graph context, do some inference, and keep the results. Then I create another context and do the same sort of thing. Finally, I create a new object based on a loss between the object and the features extracted in the first two steps. The inputs are large and unless I clean up the graphs from the first two steps, I run out of memory.

What's the best way handle this? Do I have make a new copy of the kernels (and all the other weights) for each graph? These are large models, making copies is not very efficient.

**Comment by DirkToewe** [comment]
Ideally, the Graph only describes the computation and does not contain any concrete data. It should never be larger than a few kilobytes of memory. Think of the Graph as another representation of code. 

That code is executed using a `Session`. Multiple Sessions can run the same program/Graph at the same time without conflicts (just like two processes can execute the same code). Each `Session` has its own independent state (variables). Computation inputs are represented as `tf.placeholder` in the Graph.

If You run into memory issues during the execution of a larger operation, You can simply split it into multiple smaller operations and execute them one after another calling `sess.run()` multiple times. Those operations may reside in the same Graph just fine. Let me give You can example with two operations `f` and `g` running one after another feeding the output from `f` as input to `g`:
```scala
val x = tf.placeholder[Float]( name="x")
val f = x*2
val g = x*x

val sess = Session()
try {
  val Seq(a: Tensor[Float]) = sess.run( FeedMap( x -> Tensor[Float](3) ), Seq(f) )
  val Seq(b: Tensor[Float]) = sess.run( FeedMap( x -> a ), Seq(g) )

  println( b.summarize() ) // <- b = (2*3)*(2*3) = 36
}
finally {
  sess.close()
}
```
For backpropagation You will now also have to feed back gradients from `g` to `f` which is quite cumbersome. Only do this if You have exhausted all other options. I only had to do this once to replace a `tf.while_loop`. Normally Tensorflow is doing a fine job with memory management all by itself.

One common reason for the Graph getting too large is that You unintentionally keep adding more and more operations. Try to keep the Graph building and execution in two completely separate places. Note that if You do the following:
```scala
val output: Output[Float] = Tensor.randn(Float, Shape(1000,1000))
```
which is equivalent to:
```scala
val tensor: Tensor[Float] = Tensor.randn(Float, Shape(1000,1000))
val output: Output[Float] = tf.constant(tensor)
```
What's actually happening is that You first create a Tensor (which is like a NumPy ndarray) and then You turn it into a constant added to the Graph. If `tensor` is large, Your Graph becomes large as well. Consider using `tf.randomNormal` or a `tf.variable` with `RandomNormalInitializer` instead.

**Comment by evanthomas** [comment]
Thanks for the detailed response. I will digest and try to rework my code.  The tensor in the example was just to reproduce the problem, the kernels I'm using are loaded from VCG19. I'm also working with large images and fairly complex computations. But even so, I don't really understand why the memory demand is so high - so I'm very happy to improve memory utilisation. 

Will multiple `sess.run` result in a lot transfer to the GPU?

**Comment by DirkToewe** [comment]
As far as I know that should not be an issue. You can move `Tensor` objects to the GPU before feeding them to `sess.run`, but this only makes sense if You feed it multiple times. `Tensor` objects returned by `sess.run` on the other hand should already be on the GPU. You can verify this by looking at the `Tensor.device` string.
```scala
val tensorCPU: Tensor[Float] = Tensor.randn(Float, Shape(3, 3, 3, 64))
val tensorGPU = tensorCPU.gpu(0)
println(tensorCPU.device)
println(tensorGPU.device)
```
