### ISSUE TITLE
precompiled installation not working

### ISSUE THREAD

**Issue by howarth** [eaplatanios/tensorflow_scala#19]
Hello, 

I can't get this to compile on GPU3

I downloaded the precompiled binaries at https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.3.0-rc0.tar.gz

I set my LD_LIBRARY_PATH:

```
dhowarth@gpu3:~/tensorflow_scala$ echo $LD_LIBRARY_PATH
/share/apps/tensorflow1.3/lib/
dhowarth@gpu3:~/tensorflow_scala$ ls $LD_LIBRARY_PATH
libtensorflow.so
```

And then attempted to compile:

```
dhowarth@gpu3:~/tensorflow_scala$ sbt compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /usr0/home/dhowarth/tensorflow_scala/project
[info] Set current project to all (in build file:/usr0/home/dhowarth/tensorflow_scala/)
[info] Building library with native build tool CMake.
[info] -- Found JNI: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjawt.so
[error] CMake Error at CMakeLists.txt:24 (message):
[info] -- JNI include directories: /usr/lib/jvm/java-8-oracle/include;/usr/lib/jvm/java-8-oracle/include/linux;/usr/lib/jvm/java-8-oracle/include
[error]   Library `tensorflow` not found.
[info] -- Configuring incomplete, errors occurred!
[error]
[info] See also "/usr0/home/dhowarth/tensorflow_scala/jni/target/native/linux-x86_64/build/CMakeFiles/CMakeOutput.log".
[error]
java.lang.RuntimeException: Failed to build the native library. Exit code: 1.
	at scala.sys.package$.error(package.scala:27)
	at BuildTool$ConfigureMakeInstall$Instance$class.libraries(BuildTool.scala:59)
	at BuildTool$CMake$$anon$3.libraries(BuildTool.scala:111)
	at JniNative$$anonfun$settings$7.apply(JniNative.scala:96)
	at JniNative$$anonfun$settings$7.apply(JniNative.scala:90)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (jni/*:nativeCompile) Failed to build the native library. Exit code: 1.
[error] Total time: 0 s, completed Aug 1, 2017 10:55:56 AM
```

**Comment by eaplatanios** [comment]
This has been fixed on the server.
