### ISSUE TITLE
IndexOutOfBoundsException in Tensor.hashCode

### ISSUE THREAD

**Issue by evanthomas** [eaplatanios/tensorflow_scala#53]
This reproduces the issue:
```
import java.nio.{ByteBuffer, FloatBuffer}

import org.platanios.tensorflow.api._

import scala.util.Random

object TensorTest {

  def main(args: Array[String]): Unit = {
    val shape = Shape(3, 3, 3, 64)
    val floats = FloatBuffer.allocate(shape.numElements.asInstanceOf[Int])
    val r = new Random()

    for {
      i1 <- 0 until shape(0)
      i2 <- 0 until shape(1)
      i3 <- 0 until shape(2)
      i4 <- 0 until shape(3)
    } {
      val x = r.nextFloat()
      floats.put(x)
    }

    val buffer = ByteBuffer.allocate(floats.capacity()*4)
    buffer.asFloatBuffer().put(floats)

    val t = Tensor.fromBuffer(FLOAT32, shape, shape.numElements, buffer)

    println(t.hashCode())

  }
}
```

Here is the stack trace:
```
2017-11-22 22:37:21.272 [main] INFO  TensorFlow Native - Extracting the 'tensorflow_framework' native library to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_framework.so.
2017-11-22 22:37:21.395 [main] INFO  TensorFlow Native - Copied 16095074 bytes to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_framework.so.
2017-11-22 22:37:21.396 [main] INFO  TensorFlow Native - Extracting the 'tensorflow' native library to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow.so.
2017-11-22 22:37:21.878 [main] INFO  TensorFlow Native - Copied 123079576 bytes to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow.so.
2017-11-22 22:37:21.879 [main] INFO  TensorFlow Native - Extracting the 'tensorflow_jni' native library to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_jni.so.
2017-11-22 22:37:21.882 [main] INFO  TensorFlow Native - Copied 654744 bytes to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_jni.so.
2017-11-22 22:37:21.930 [main] INFO  TensorFlow Native - Extracting the 'tensorflow_ops' native library to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_ops.so.
2017-11-22 22:37:21.930 [main] INFO  TensorFlow Native - Copied 48552 bytes to /tmp/tensorflow_scala_native_libraries6280890813175449973/libtensorflow_ops.so.
2017-11-22 22:37:21.945766: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-22 22:37:22.072853: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-22 22:37:22.073189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1064] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:09:00.0
totalMemory: 5.93GiB freeMemory: 4.65GiB
2017-11-22 22:37:22.073209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1154] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:09:00.0, compute capability: 6.1)
2017-11-22 22:37:22.516454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1154] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:09:00.0, compute capability: 6.1)
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.getFloat(DirectByteBuffer.java:867)
	at org.platanios.tensorflow.api.types.FLOAT32$.getElementFromBuffer(DataType.scala:398)
	at org.platanios.tensorflow.api.types.FLOAT32$.getElementFromBuffer(DataType.scala:379)
	at org.platanios.tensorflow.api.tensors.Tensor$$anon$1.next(Tensor.scala:268)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at org.platanios.tensorflow.api.tensors.Tensor$$anon$1.foreach(Tensor.scala:244)
	at org.platanios.tensorflow.api.tensors.Tensor.hashCode(Tensor.scala:360)
	at co.mumbler.imageai.server.launch.TensorTest$.main(TensorTest.scala:31)
	at co.mumbler.imageai.server.launch.TensorTest.main(TensorTest.scala)

Process finished with exit code 1
```

Not urgent from my point of view, I'll just work around it.

**Comment by eaplatanios** [comment]
@evanthomas The third argument of the `Tensor.fromBuffer` method is supposed to be the number of bytes to read from the buffer and not the number of elements. The reason that's needed is because string tensors don't have a fixed element size and thus their size in terms of number of bytes cannot be inferred from their shape. If you change to the following line, your code will work. :)

```scala
val t = Tensor.fromBuffer(FLOAT32, shape, shape.numElements * FLOAT32.byteSize, buffer)
```

**Comment by evanthomas** [comment]
@eaplatanios Doh! This also fixes a segv in JNI that I was trying to figure out.
