### ISSUE TITLE
libtensorflow_ops.so: undefined symbol

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#66]
With the current snapshot buiId from sonatype I get the following error when running on GPU (CPU seems to work fine).
```
[error] java.lang.ExceptionInInitializerError
[errlor]         at org.platanios.tensorflow.jni.Tensor$.<init>(Tensor.scala:24)
[error]         at org.platanios.tensorflow.jni.Tensor$.<clinit>(Tensor.scala)
[error]         at org.platanios.tensorflow.api.tensors.Context$.apply(Context.scala:50)
[error]         at org.platanios.tensorflow.api.package$.<init>(package.scala:89)
[error]         at org.platanios.tensorflow.api.package$.<clinit>(package.scala)
...
[error] Caused by: org.platanios.tensorflow.jni.NotFoundException: /tmp/tensorflow_scala_native_libraries2791204661633142264/libtensorflow_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesESt16initializer_listINS_11StringPieceEE

```

**Comment by sbrunk** [comment]
Only saw now that this is a duplicate of #64
